version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: 
      CELERY_BROKER: ${REDIS_URI}
      CELERY_BACKEND: ${REDIS_URI}

  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/code
    environment:
      CELERY_BROKER: ${REDIS_URI}
      CELERY_BACKEND: ${REDIS_URI}
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - web
      - redis  
      - db
      - celery

  redis:
    image: "redis:alpine"      
  db:
    image: postgres:13
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
        - "5432:5432"  
    restart: always    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
  
