# Generated by Django 3.1.3 on 2020-11-25 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_remove_profile_created'),
        ('expenses', '0016_auto_20201107_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Earns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.CharField(max_length=800, verbose_name='Descrição')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='earns.category', verbose_name='Categoria')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.currencies')),
            ],
            options={
                'verbose_name': 'Ganhos',
                'ordering': ['-date'],
            },
        ),
    ]
