# Generated by Django 3.1.3 on 2020-11-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earns',
            options={'ordering': ['-date'], 'verbose_name': 'Ganho', 'verbose_name_plural': 'Ganhos'},
        ),
        migrations.AddField(
            model_name='earns',
            name='long_term',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ganho fixo'),
        ),
    ]
