# Generated by Django 3.1.3 on 2020-11-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earns', '0002_auto_20201130_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earns',
            name='long_term',
            field=models.BooleanField(default=False, verbose_name='Ganho fixo'),
        ),
    ]
