# Generated by Django 3.1.3 on 2020-12-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earns', '0003_auto_20201130_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earns',
            options={'ordering': ['-long_term'], 'verbose_name': 'Ganho', 'verbose_name_plural': 'Ganhos'},
        ),
    ]
