# Generated by Django 3.1.3 on 2020-11-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor'),
        ),
    ]
