# Generated by Django 3.1.3 on 2020-11-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_created'),
        ('expenses', '0002_auto_20201105_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='profiles.profile'),
        ),
    ]
