# Generated by Django 3.1.3 on 2020-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20201105_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField()),
                ('symbol', models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
    ]
