# Generated by Django 3.1.3 on 2020-11-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20201106_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencies',
            old_name='name',
            new_name='code',
        ),
    ]
