# Generated by Django 3.1.3 on 2020-11-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20201106_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='code',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='symbol',
            field=models.JSONField(default={}),
        ),
    ]
