# Generated by Django 3.1.3 on 2020-11-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20201106_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='code',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='symbol',
        ),
        migrations.AddField(
            model_name='currencies',
            name='currency',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
