# Generated by Django 3.1.3 on 2020-11-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_auto_20201106_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='currency',
            field=models.TextField(default=None, verbose_name='Moeda'),
        ),
    ]
