# Generated by Django 3.1.3 on 2020-11-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20201106_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='currency',
            field=models.CharField(default=None, max_length=20, verbose_name='Moeda'),
        ),
    ]
