# Generated by Django 3.1.3 on 2020-11-07 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_auto_20201106_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.currencies'),
        ),
    ]
