# Generated by Django 3.1.3 on 2020-11-30 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_auto_20201107_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.currencies', verbose_name='Moeda'),
        ),
    ]
