# Generated by Django 3.1.3 on 2020-12-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_auto_20201130_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='long_term',
            field=models.BooleanField(default=False, verbose_name='Gasto fixo'),
        ),
    ]
